const cities = [
"Addis Ababa (Adis Ababa)",
"Gondar (Gonder )",
"Mekele",
"Adama (Nazret)",
"Awasa (Hawassa)",	
"Bahir Dar",	
"Dire Dawa (Dire Dewa)",
"Dessie (Desie)",
"Jimma (Jima )",
"Jijiga",
"Shashemene (Shashamane)",
"Wolayta Sodo (Sodo)",
"Debre Zeyit (Bishoftu)",	
"Arba Minch",	
"Hosaena (Hosaina )",	
"Harer (Harar)",	
"Dilla (Dila)",	
"Nekemte",
"Debre Birhan (Debre Berhan)",	
"Debre Markos (Debre Marqos)",	
"Assela (Asella; Asela)",	
"Kombolcha (Kembolcha )",	
"Debre Tabor",	
"Adigrat",	
"Arsi Negele",	
"Weldiya",
"Sebeta",	
"Burayu",	
"Shire (Inda Silase)",	
"Ambo (Hagere Hiywet)",	
"Gambela",
"Aksum (Axum)",	
"Mizan Teferi (Mizan )",
"Bale Robe (Robe)",
"Butajira",
"Ziway",	
"Areka",	
"Yirga Alem",
"Mojo",
"Welkite",	
"Woliso",
"Meki",
"Gode",	
"Kobo",
"Alaba Kulito (Kolito)",
"Negele Borena (Negele )",
"Alamata",
"Adwa",
"Asebe Teferi (Chiro)",
"Teppi (Tepi)",	
"Assosa (Asosa)",	
"Durame",	
"Metema",	
"Hagere Maryam (Hagere Mariam)",	
"Goba",	
"Boditi",	
"Dolo",	
"Wikro (Wukro)",
"Hadero",	
"Azezo",
"Alem Maya (Haromaya)",
"Gimbi",
"Wondo Genet",
"Sawla (Felege Neway)",
"Wendo (Aleta Wendo)",
"Metu",
"Dembi Dolo",
"Bure",
"Finote Selam",
"Moyale",
"Fiche",
"Bonga",
"Jinka",
"Agaro",	
"Motta (Mota)",	
"Gelemso",	
"Degeh Bur (Degehabur)",	
"Chuko",	
"Nedjo (Nejo)",	
"Kebri Dehar (Kebri Dahar)",	
"Sekota (Soqota)",	
"Dangla (Dangila)",	
"Maychew",	
"Bekoji",	
"Holeta (Holata)",	
"Kibre Mengist (Kebri Mangest)",	
"Shakiso",	
"Baco (Bako)",	
"Gorgora",	
"Chagni (Chagne)",	
"Debark (Debarq)",	
"Humera (Himora)",	
"Deder",	
"Dodola",	
"Kemise (Kemisie)",	
"Shinshicho",	
"Asasa",	
"Wereta (Werota)",
"Shone",	
"Metehara",	
"Injibara",	
"Ginchi",	
"Ginir",	
"Yirga", 
"Gebre Guracha (Kuyu)",	
"Bedele",	
"Dembecha",	
"Dera",	
"Nefas Mewcha",	
"Robe (Arsi Robe)",	
"Adet",	
"Asayita (Asaita)",
"Bedesa",	
"Mer Awi (Merawi)",	
"Bati",	
"Babile (Babille)",	
"Chencha",	
"Shiraro",	
"Gidole",	
"Korem",	
"Dabat",	
"Shewa Robit",	
"Tis Abay",	
"Lalibela",	
"Abiy Adi (Abi Adi)",	
"Leku",	
"Iteya",	
"Yebelo",	
"Bichena",	
"Addis Zemen",	
"Mersa",	
"Welenchiti",	
"Kofele",	
"Awash",	
"Dubti",	
"Shambu",	
"Ayikel (Chilga)",	
"Tulu Bolo",	
"Logia",	
"Wonji (Wenji Gefersa)",	
"Mendi",	
"Guder",	
"Derwernache (Derwonaji)",
"Gutin",	
"Mekane Yesus",	
"Abomsa",	
"Huruta (Hurata)",
"Guracha Jeldu",	
"Hartisheik (HartiShek)",	
"Tog Wajale (Togochale)",
"Mehoni (Mekhoni)",	
"Sokoru",	
"Mieso",	
"Konso",	
"Were Ilu",	
"Sendafa",	
"May Cadera (May Kadera)",
"Hirna",	
"Addi Arkay",	
"Ginde Beret",	
"Addis Alem (Ejere)",
"Awubere (Awuberre)",	
"Imi",	
"Debre Sina",
"Dejen",
"Gore",
"Debre Werk",
"Hagere Selam",	
"Gewana (Gewane)",	
"Werder (Warder)",	
"Sire (Sirie)",
"Dukem",
"Seka Chekorsa",	
"Mega",	
"Ankober",
"Langano"
]

const regions = [
    "Afar", 
    "Amhara", 
    "Oromia", 
    "Somali", 
    "Benishangul-Gumuz", 
    "Gambella", 
    "Sidama", 
    "Tigray", 
    "Southern Nations Nationalities and People Region (SNNPR)", 
    "South West Ethiopia Peoples' Region (SWEPR)",
    "Harari",
    "Addis Ababa City administration",
    "Dire Dawa city council"
]

export default  {
    cities,
    regions
}