export { default as Banner } from './Banner/Banner'
export { default as Categories } from './Categories/Categories'
export { default as Featured } from './Featured/Featured'
export { default as Navbar } from './Navbar/Navbar'
export { default as Product } from './Product/Product'
export { default as Products } from './Products/Products'
export { default as Cart } from './Cart/Cart'